export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAIL = "FETCH_DATA_FAIL";
export const SAVE_DATA="SAVE_DATA"
export const UPDATE_DATA="UPDATE_DATA"
export const REMOVE_SELECTED_ITEM="REMOVE_SELECTED_ITEM"
export const USER_AUTH="USER_AUTH"